# Generated by Django 3.2.3 on 2023-12-20 19:56

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_enquiryticket_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryticket',
            name='completion_date',
            field=models.DateField(blank=True, help_text='(optional)', null=True, validators=[ticket.models.validate_not_in_past]),
        ),
        migrations.AlterField(
            model_name='enquiryticket',
            name='description',
            field=models.TextField(help_text='What do you want printed and what dimensions, colors, finishes etc.', max_length=400),
        ),
        migrations.AlterField(
            model_name='enquiryticket',
            name='title',
            field=models.CharField(help_text='Your project or item name', max_length=100),
        ),
    ]
