# Generated by Django 3.2.3 on 2023-12-23 04:53

import datetime
from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20231220_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryticket',
            name='completion_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today, help_text='(optional)', null=True, validators=[ticket.models.validate_not_in_past]),
        ),
    ]
