# Generated by Django 3.2.3 on 2023-12-23 05:29

import datetime
from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_enquiryticket_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryticket',
            name='completion_date',
            field=models.DateTimeField(default=datetime.date.today, help_text='If not time-sensitive please submit 12/12/2024', validators=[ticket.models.validate_not_in_past]),
        ),
    ]
